name: codecov upload when push main
on: 
  push:
    branches:
      - main

jobs:
  npm-install_test_codecover:
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup npm
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          
      - name: npm dependecies
        run: npm ci
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
           token: ${{ secrets.CODECOV_TOKEN }}
